In [1]:
import numpy as np

In [7]:
a=np.array([1,2,3],dtype='int8')
b=np.array([1,3,5],dtype='int8')
print(a*b)

[ 1  6 15]


In [11]:
b=np.array([[9,8,7.5],[6,5,2.5]],dtype='float32')
print(b)

[[9.  8.  7.5]
 [6.  5.  2.5]]


In [12]:
# get dimension
print(a.ndim)
print(b.ndim)

1
2


In [13]:
# shape
print(a.shape)
print(b.shape)

(3,)
(2, 3)


In [18]:
# memory usage
print(a.dtype)
print(a.size) 
print(a.itemsize)
print(a.nbytes)
print(b.nbytes)

int8
3
1
3
24


In [19]:
a=np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(a)
print(a.shape)
print(a.ndim)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]
(2, 7)
2


In [21]:
# access array [row, col]
print(a[1,5])
print(a[1,-2])

13
13


In [23]:
# get a specific row/col
print(a[0,])
print(a[0,:])

[1 2 3 4 5 6 7]
[1 2 3 4 5 6 7]


In [27]:
# step indexing
print(a[:,1:6:2])

[[ 2  4  6]
 [ 9 11 13]]


In [28]:
# change entry
a[1,5]=48
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 48 14]]


In [30]:
a[:,2]=5
print(a)
a[:,2]=[99,100]
print(a)

[[ 1  2  5  4  5  6  7]
 [ 8  9  5 11 12 48 14]]
[[  1   2  99   4   5   6   7]
 [  8   9 100  11  12  48  14]]


In [33]:
# all zeros
a=np.zeros(4)
print(a)
a=np.zeros((2,3))+1.2
print(a)

[0. 0. 0. 0.]
[[1.2 1.2 1.2]
 [1.2 1.2 1.2]]


In [34]:
# all ones
a=np.ones((4,3,2))
print(a)

[[[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]]


In [36]:
# any other number
a=np.full((3,4),99)
print(a)

[[99 99 99 99]
 [99 99 99 99]
 [99 99 99 99]]


In [37]:
# full like
a=np.full_like(a,15)
print(a)

[[15 15 15 15]
 [15 15 15 15]
 [15 15 15 15]]


In [42]:
# random numbers
a=np.random.rand(4,2)
print(a)
a=np.random.normal(loc=0,scale=0.5,size=(3,2))
print(a)
a=np.random.random_sample(a.shape)
print(a)

[[0.5941391  0.97358992]
 [0.62642854 0.79953475]
 [0.50521458 0.5794699 ]
 [0.10490567 0.61214718]]
[[-0.40246954  0.55419756]
 [-0.43268798  0.76770323]
 [-1.78476112 -0.62248789]]
[[0.10893312 0.12230171]
 [0.02715743 0.48126487]
 [0.81693202 0.28318455]]


In [46]:
# random intergers
a=np.random.randint(-10,15,(4,5))
print(a)

[[ -8  14  13  14  13]
 [ -4  -8   0   9  -2]
 [ 11  10   6 -10  -2]
 [ -4   3  14   0  12]]


In [47]:
# identity matrix
a=np.identity(4)
print(a)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [53]:
# repeat array
a=np.array([[1,2,3,4]])
a=np.repeat(a,3,axis=0)
print(a)
print(a.ndim)
print(a.shape)

[[1 2 3 4]
 [1 2 3 4]
 [1 2 3 4]]
2
(3, 4)


In [56]:
# be careful when copying
b=a;print(b)
b[0]=100 # override
print(b);print(a)
c=b.copy()
c[0]=999 # no override
print(b);print(c)

[[100 100 100 100]
 [  1   2   3   4]
 [  1   2   3   4]]
[[100 100 100 100]
 [  1   2   3   4]
 [  1   2   3   4]]
[[100 100 100 100]
 [  1   2   3   4]
 [  1   2   3   4]]
[[100 100 100 100]
 [  1   2   3   4]
 [  1   2   3   4]]
[[999 999 999 999]
 [  1   2   3   4]
 [  1   2   3   4]]


In [61]:
# basic math
a=np.array([1,2,3,4,5])
print(a)
print(a+2)
print(a**2)
print(a/2)
print(a%3)
print(a//3)
print(np.sin(a))

[1 2 3 4 5]
[3 4 5 6 7]
[ 1  4  9 16 25]
[0.5 1.  1.5 2.  2.5]
[1 2 0 1 2]
[0 0 1 1 1]
[ 0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427]


In [62]:
# Linear algebra
a=np.full((2,3),1);print(a)
b=np.full((3,2),2);print(b)

[[1 1 1]
 [1 1 1]]
[[2 2]
 [2 2]
 [2 2]]


In [64]:
print(a @ b)
print(np.dot(a,b))
print(np.matmul(a,b))

[[6 6]
 [6 6]]
[[6 6]
 [6 6]]
[[6 6]
 [6 6]]


In [66]:
c=np.identity(3)
print(np.linalg.det(c))
print(np.linalg.eig(c))

1.0
(array([1., 1., 1.]), array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]]))


In [69]:
# statistics
stats=np.array([[1,2,3],[4,5,6]])
print(stats)
print(np.min(stats))
print(np.min(stats,axis=0))
print(np.min(stats,axis=1))
print(np.sum(stats))
print(np.sum(stats, axis=0))
print(np.sum(stats, axis=1))

[[1 2 3]
 [4 5 6]]
1
[1 2 3]
[1 4]
21
[5 7 9]
[ 6 15]


In [72]:
# Reorgnizing arrays
before=np.array([[1,2,3,4],[5,6,7,8]])
print(before.shape)
after=before.reshape((8,1))
print(after)
after=before.reshape((2,2,2))
print(after)
after=before.reshape((2,5))
print(after)

(2, 4)
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]]
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


ValueError: cannot reshape array of size 8 into shape (2,5)

In [74]:
# stacking

# vstack
v1=np.array([1,2,3,4])
v2=np.array([5,6,7,8])
print(np.vstack([v1,v2]))

# hstack
print(np.hstack([v1,v2]))

[[1 2 3 4]
 [5 6 7 8]]
[1 2 3 4 5 6 7 8]


In [75]:
# Advanced indexing
a=np.random.RandomState(312).uniform(-50,50,size=(10,3))
print(a)

[[-28.32731207  -8.12779801  -8.57172058]
 [-32.97218665  36.61464927  12.06778212]
 [ -6.38952408  18.4504864  -43.96407843]
 [ 42.73046466 -38.26340943  16.29520708]
 [-11.23653295  37.96521411 -19.59953814]
 [  9.11050226 -41.24900818 -40.35935114]
 [ 11.79647606  23.99626792  37.4547864 ]
 [ 38.95414577 -41.22844445  18.33955197]
 [-41.15348347  47.14041864 -28.96778764]
 [ 18.57088944 -21.18212591   9.21830668]]


In [76]:
selected=a>25
print(selected)

[[False False False]
 [False  True False]
 [False False False]
 [ True False False]
 [False  True False]
 [False False False]
 [False False  True]
 [ True False False]
 [False  True False]
 [False False False]]


In [77]:
print(a[selected])

[36.61464927 42.73046466 37.96521411 37.4547864  38.95414577 47.14041864]


In [82]:
print(a[[1,5,8],:])

[[-32.97218665  36.61464927  12.06778212]
 [  9.11050226 -41.24900818 -40.35935114]
 [-41.15348347  47.14041864 -28.96778764]]


In [84]:
print(np.any(a>30,axis=0))
print(np.any(a>30,axis=1))

[ True  True  True]
[False  True False  True  True False  True  True  True False]


In [87]:
print((a>20) & ~(a<35))

[[False False False]
 [False  True False]
 [False False False]
 [ True False False]
 [False  True False]
 [False False False]
 [False False  True]
 [ True False False]
 [False  True False]
 [False False False]]
